### ISSUE TITLE
Vapor 3: downloading any static asset from within Public crashes vapor server process

### ISSUE THREAD

**Issue by masonmark** [vapor/vapor#1485]
* Vapor Version: beta (tip of beta branch as of 2018-02-07 (51e85d8fde64b7f1a402d43096ab1b1a4477a1f8))
* OS: macOS
* OS Version: 10.13.3
* Vapor Toolbox Version: 3.1.3
* Swift toolchain: 4.1-DEVELOPMENT-SNAPSHOT-2018-02-01-a

### Expected Behavior

Downloading a static asset, such as `./Public/favicon.png` does download the asset.

### Current Behavior

Attempting the download crashes the server process:

```
Fatal error: file /Users/mason/bug_demo/.build/checkouts/engine.git-3311994267206676365/Sources/HTTP/Serializer/HTTPSerializer.swift, line 129
```

### How to Reproduce

1. Make a new vapor project with `vapor new bug_demo --branch=beta`

2. Add an image at `Public/favicon.png`

3. Build and run the project

4. Hit the `http://localhost:8080/favicon.png` URL

5. Note that it crashed.

### Discussion

I poked at this in Xcode, and it seems that this is an integration issue between Vapor and the HTTP package. The HTTP package is throwing the error intentionally. In Xcode, after execution stops with `codes.vapor.engine.server.worker.11 (2): Fatal error` (at `HTTPSerializer.swift:129`), I used the `lldb` debugger command line to inspect the `message` object:

```
(lldb) po message
▿ (HTTPResponse)
Content-Length: 0
Content-Type: image/png
Transfer-Encoding: chunked
Date: Wed, 07 Feb 2018 07:10:11 GMT

Error collecting body data: ⚠️ [HTTP.HTTPError.chunkedBody: Cannot use `makeData(max:)` on a chunk-encoded body.] [/Users/mason/SORACOM/vaquero/Vaquero/.build/checkouts/engine.git-3311994267206676365/Sources/HTTP/Message/HTTPBody.swift:223:34]
  ▿ version : HTTPVersion
    - major : 1
    - minor : 1
  ▿ status : HTTPStatus
    - code : 200
    ▿ messageBytes : 2 elements
      - 0 : 79
      - 1 : 75
  ▿ headers : Content-Length: 0
Content-Type: image/png
Transfer-Encoding: chunked
Date: Wed, 07 Feb 2018 07:10:11 GMT

    ▿ storage : Content-Length: 0
Content-Type: image/png
Transfer-Encoding: chunked
Date: Wed, 07 Feb 2018 07:10:11 GMT

  ▿ body : Error collecting body data: ⚠️ [HTTP.HTTPError.chunkedBody: Cannot use `makeData(max:)` on a chunk-encoded body.] [/Users/mason/SORACOM/vaquero/Vaquero/.build/checkouts/engine.git-3311994267206676365/Sources/HTTP/Message/HTTPBody.swift:223:34]
    ▿ storage : HTTPBodyStorage
      - chunkedOutputStream : (Function)
  - onUpgrade : nil

(lldb) 
```

So the issue seems to be at the integration boundary between `vapor` itself and the HTTP library from `vapor/engine`. Unfortunately, I'm not familiar enough with the interoperation between these components to write a failing test case for this; this bug report will have to suffice.

### Full reproduction steps in terminal

(Note that this transcript uses `swift build` instead of `vapor build`, and the Xcode project-generation step fails, because of an incompatibility between Vapor Toolbox and the current Swift 4.1 betas.)

```
[mason@iMac-Pro-No-5 ~]$ swift --version
Apple Swift version 4.1-dev (LLVM 4d75b446be, Clang db92199adc, Swift 4cb7e7f233)
Target: x86_64-apple-darwin17.4.0
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$ swiftenv global
4.1-DEVELOPMENT-SNAPSHOT-2018-02-01-a
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$ vapor --version
Vapor Toolbox: 3.1.3
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$ date
Wed Feb  7 15:55:33 JST 2018
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$
[mason@iMac-Pro-No-5 ~]$ vapor new bug_demo --branch=beta
Cloning Template [Done]
Updating Package Name [Done]
Initializing git repository [Done]

                                                                          **
                                                                        **~~**
                                                                      **~~~~~~**
                                                                    **~~~~~~~~~~**
                                                                  **~~~~~~~~~~~~~~**
                                                                **~~~~~~~~~~~~~~~~~~**
                                                              **~~~~~~~~~~~~~~~~~~~~~~**
                                                             **~~~~~~~~~~~~~~~~~~~~~~~~**
                                                            **~~~~~~~~~~~~~~~~~~~~~~~~~~**
                                                           **~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
                                                           **~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
                                                           **~~~~~~~~~~~~~~~~~~~~~++++~~~**
                                                            **~~~~~~~~~~~~~~~~~~~++++~~~**
                                                             ***~~~~~~~~~~~~~~~++++~~~***
                                                               ****~~~~~~~~~~++++~~****
                                                                  *****~~~~~~~~~*****
                                                                     *************

                                                            _       __    ___   ___   ___
                                                           \ \  /  / /\  | |_) / / \ | |_)
                                                            \_\/  /_/--\ |_|   \_\_/ |_| \
                                                              a web framework for Swift

                                                         Project "bug_demo" has been created.
                                                  Type `cd bug_demo` to enter the project directory.
                                               Use `vapor cloud deploy` to host your project for free!
                                                                        Enjoy!

[mason@iMac-Pro-No-5 ~]$ cd bug_demo
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$ vapor update
Updating [Done]
Changes to dependencies usually require Xcode to be regenerated.
Would you like to regenerate your xcode project now?
y/n> y
Generating Xcode Project [Failed]
error: unknown option --enable-prefetching; use --help to list available options

Error: Could not generate Xcode project: error: unknown option --enable-prefetching; use --help to list available options

[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$ swift build
Compile CSQLite sqlite3.c
Compile CHTTP http_parser.c
Compile Swift Module 'Debugging' (6 sources)
Compile Swift Module 'COperatingSystem' (1 sources)
Compile Swift Module 'Bits' (5 sources)
Compile Swift Module 'Logging' (3 sources)
Compile Swift Module 'SQL' (21 sources)
Compile Swift Module 'Async' (45 sources)
Compile Swift Module 'Service' (17 sources)
Compile Swift Module 'TCP' (12 sources)
Compile Swift Module 'CodableKit' (24 sources)
Compile Swift Module 'Crypto' (29 sources)
Compile Swift Module 'ServerSecurity' (1 sources)
Compile Swift Module 'TLS' (6 sources)
Compile Swift Module 'HTTP' (36 sources)
Compile Swift Module 'DatabaseKit' (17 sources)
Compile Swift Module 'Console' (21 sources)
Compile Swift Module 'Validation' (15 sources)
Compile Swift Module 'SQLite' (22 sources)
Compile Swift Module 'TemplateKit' (38 sources)
Compile Swift Module 'AppleTLS' (5 sources)
Compile Swift Module 'Command' (11 sources)
Compile Swift Module 'Fluent' (47 sources)
Compile Swift Module 'WebSocket' (9 sources)
Compile Swift Module 'Multipart' (5 sources)
Compile Swift Module 'FormURLEncoded' (13 sources)
Compile Swift Module 'FluentSQL' (13 sources)
Compile Swift Module 'FluentSQLite' (9 sources)
Compile Swift Module 'Routing' (9 sources)
Compile Swift Module 'Vapor' (62 sources)
Compile Swift Module 'App' (5 sources)
Compile Swift Module 'Run' (1 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/Run
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$
[mason@iMac-Pro-No-5 bug_demo (master)]$ vapor run
Running bug_demo ...
Migrating sqlite DB
Migrations complete
Server starting on http://localhost:8080
```

...at this point the server is running, and in my browser I hit the URL `http://localhost:8080/favicon.png`, which immediately causes a crash:

```
Fatal error: file /Users/mason/bug_demo/.build/checkouts/engine.git-3311994267206676365/Sources/HTTP/Serializer/HTTPSerializer.swift, line 129
[mason@iMac-Pro-No-5 bug_demo (master)]$
```

**Comment by tanner0101** [comment]
This was fixed here https://github.com/vapor/vapor/commit/2f7069c51a6ad7e2a30fb19d6872033b2455e1b5

**Comment by nhatlee** [comment]
Still happen with me when run `vapor xcode -y` on branch `3.0 beta`. the error is: 
```
➜  MySite3.0 git:(master) vapor xcode -y
Generating Xcode Project [Failed]
error: unknown option --enable-prefetching; use --help to list available options

Error: Could not generate Xcode project: error: unknown option --enable-prefetching; use --help to list available options

➜  MySite3.0 git:(master) 
```

**Comment by vzsg** [comment]
If you upgrade the toolbox with `brew upgrade -force vapor/tap/vapor`, the error will be gone for good.

**Comment by nhatlee** [comment]
@vzsg : after run your suggestion: `swift package generate-xcodeproj` and `vapor xcode -y` run forever :(

**Comment by vzsg** [comment]
Then I guess your project dependencies are in conflict. My "suggestion" did not really affect them.
