### ISSUE TITLE
Websockets can't send from within `.map()`

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1505]
* Vapor Version: 3.0.0-beta.3.1.2
* OS: macOS
* OS Version: 10.13.2 
* Vapor Toolbox Version: 3.1.4

### Expected Behavior
It should be possible to run a DB query or send a client request, and broadcast the result to a websocket connection.

### Current Behavior
`ws.send()` is executed but nothing is sent to the client

### How to Reproduce
```swift
router.websocket("test") { (req, ws) in
    ws.onString({ (ws, msg) in
        req.withPooledConnection(to: .psql, closure: { (conn) in
            return conn
                .query(Message.self)
                .all()
                .map(to: String.self) { allMessages in
                    let encoder = JSONEncoder()
                    guard let allJSONMessages = try encoder.encode(allMessages).toString()
                        else {throw Abort(.internalServerError)}
                    return allJSONMessages
                }.map(to: Void.self) { messageStrings in
                    ws.send(string: messageStrings)
                    return
                }
        })
    })
}
```

In this case `messageStrings` contains the correct data, but nothing is sent back to the client.

**Comment by Joannis** [comment]
@twof Locally, I'm not seeing this anymore. We fixed a few websocket bugs [5 days ago](https://github.com/vapor/engine/pull/238)

**Comment by Joannis** [comment]
Closing this issue as it's not producable on the latest Vapor 3 build, please do re-open if it's a problem.

**Comment by twof** [comment]
Still seeing this 

Route:
```swift
router.websocket("test") { (req, ws) in
    ws.onString({ (ws, msg) in
        _ = Message
            .query(on: req)
            .all()
            .map(to: String.self) { allMessages in
                let encoder = JSONEncoder()
                guard let allJSONMessages = try encoder.encode(allMessages).toString()
                    else {throw Abort(.internalServerError)}
                return allJSONMessages
            }.map(to: Void.self) { messageStrings in
                return ws.send(string: messageStrings)
        }
    })
}
```

Sample request:
```bash
$ ws ws://localhost:8080/test
> test
>
```

`return ws.send(string: messageStrings)` is getting hit and `messageStrings` contains all of my `Message`s turned into JSON strings, but nothing is returned to the websocket.

`Package.swift`
```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "MakeChatWithUs",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc"),
        .package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc.1"),
        .package(url: "https://github.com/vapor/leaf.git", from: "3.0.0-beta"),
        ],
    targets: [
        .target(name: "App", dependencies: [
            "Vapor",
            "FluentPostgreSQL",
            "Leaf"
            ]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"]),
        ]
)
```

Config:
```swift
public func configure(
    _ config: inout Config,
    _ env: inout Environment,
    _ services: inout Services
) throws {
    let router = EngineRouter.default()
    services.register(router, as: Router.self)

    try services.register(FluentPostgreSQLProvider())

    let psqlDatabaseConfig = PostgreSQLDatabaseConfig(hostname: "redacted", port: 5433, username: "redacted")
    var databaseConfig = DatabaseConfig()

    let db = PostgreSQLDatabase(config: psqlDatabaseConfig)
    databaseConfig.add(database: db, as: .psql)
    services.register(databaseConfig)

    var migrationConfig = MigrationConfig()
    migrationConfig.add(model: Message.self, database: .psql)
    services.register(migrationConfig)
}

extension DatabaseIdentifier {
    static var psql: DatabaseIdentifier<PostgreSQLDatabase> {
        return .init("psql")
    }
}
```

Working Websocket route:
```swift
router.websocket("ping") { (req, ws) in
    ws.onString({ (ws, msg) in
        if msg == "ping" {
            ws.send(string: "pong")
        }
    })
}
```

Working HTTP route:
```swift
router.get("messages") { (req) in
    return Message.query(on: req).all()
}
```

**Comment by tanner0101** [comment]
Seems to work for me 🤔 

```swift
/// Register your application's routes here.
///
/// [Learn More →](https://docs.vapor.codes/3.0/getting-started/structure/#routesswift)
public func routes(_ router: Router) throws {
    // Basic "Hello, world!" example
    router.get("hello") { req in
        return "Hello, world!"
    }

    router.websocket("test") { (req, ws) in
        ws.onString { ws, msg in
            print("Got: " + msg)
            _ = Message.query(on: req).all().map(to: String.self) { allMessages in
                guard let allJSONMessages = try String(data: JSONEncoder().encode(allMessages), encoding: .ascii) else {
                    throw Abort(.internalServerError)
                }
                return allJSONMessages
            }.map(to: Void.self) { messageStrings in
                print(messageStrings)
                return ws.send(string: messageStrings)
            }
        }
    }
}
```

```sh
~/dev/tanner0101/twof-ws master$ wsc ws://localhost:8080/test
Connected to ws://localhost:8080/test
> hi
< [{"id":1,"text":"hi"},{"id":2,"text":"sup"},{"id":3,"text":"vapor rulez"}]
> 
```

**Comment by tanner0101** [comment]
[twof-ws.zip](https://github.com/vapor/vapor/files/1765850/twof-ws.zip)

**Comment by tanner0101** [comment]
🎉 https://github.com/vapor/engine/releases/tag/3.0.0-rc.1.0.1

**Comment by twof** [comment]
Thanks so much!
