### ISSUE TITLE
FileIO support range header

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/vapor#1762]
I use `FileMiddleware` on the localhost to access files from `Public` folder.
And it looks like it works, but I'm experiencing problems with mp4 files in that folder.

### Steps to reproduce

Put ~1MB mp4 file into Public folder and try to open it from browser like http://localhost:8080/movie.mp4 and browser will show you something like that

<img width="426" alt="2018-07-20 12 40 02" src="https://user-images.githubusercontent.com/1272610/42992612-141944b2-8c1a-11e8-8d68-71cf06c80692.png">

### Expected behavior

Video file should be available to download/open.

### Actual behavior

Images with size ~200Kb works perfectly, but ~1Mb mp4 files not.
Example file [exampleVideo.zip](https://github.com/vapor/vapor/files/2213163/exampleVideo.zip)

### Environment
* Vapor Framework version: 3.0.6
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13.6 (17G65)

**Comment by MihaelIsaev** [comment]
I realized that error raised somwhere here

<img width="892" alt="2018-07-20 12 52 03" src="https://user-images.githubusercontent.com/1272610/42993201-d7666bf6-8c1b-11e8-8b4a-d52da7ea7b52.png">

It throws: 
`chunkedStream error: ioOnClosedChannel. The operation couldn’t be completed. (NIO.ChannelError error 4.)`

And I have no idea how to fix that... 🤭

**Comment by andreasley** [comment]
I assume you're using Safari and the same video works fine in Firefox or Chrome, correct?

When loading media (e.g. mp4 files), Safari first sends a request with the following HTTP header, probably to find out if the server supports byte ranges:
`Range: bytes=0-1`
This has been the case for both macOS and iOS for a few years.

Vapor simply ignores the `Range` header and responds with the whole file, which Safari doesn't seem to like. I think the solution would be to honor `Range` request headers in `FileMiddleware`/`FileIO`.

**Comment by Noobitious** [comment]
I agree this is a problem. Safari doesn't work, even though Chrome works fine.

**Comment by MihaelIsaev** [comment]
I faced with that problem when AVPlayer in my iOS app was unable to play video files from my vapor server. So it looks like all Apple's products use the same core.
In production good solution is to use nginx for static files, but it's not always convenient to use nginx+vapor while local development (though I use it now because of that issue).

**Comment by tanner0101** [comment]
This is very likely related to some bugs fixed in recent versions of vapor/http. (see https://github.com/vapor/http/releases/tag/3.1.4). Would you mind running `swift package update` and testing again?

**Comment by LoganWright** [comment]
Just confirmed this is still an issue and updated title a bit.

The issue is w/ the range header, you could build a replacement FileMiddleware to accept this quick and hacky, but the RFC is a bit in depth and we'll have to be more thorough for the framework implementation.

**Comment by twof** [comment]
```swift
//
// PhileFileMiddleware.swift
// App
//
// Created by Joe Kramer on 2/6/19.
//
​
import Foundation
import HTTP
import Vapor
​
/// Servers files from the supplied public directory
/// on not found errors.
public final class PhileFileMiddleware: Middleware, ServiceType {
  /// See `ServiceType`.
  public static func makeService(for container: Container) throws -> PhileFileMiddleware {
    return try .init(publicDirectory: container.make(DirectoryConfig.self).workDir + "Public/")
  }
  
  /// The public directory.
  /// - note: Must end with a slash.
  private let publicDirectory: String
  
  /// Creates a new `PhileFileMiddleware`.
  public init(publicDirectory: String) {
    self.publicDirectory = publicDirectory.hasSuffix("/") ? publicDirectory : publicDirectory + "/"
  }
  
  /// See `Middleware`.
  public func respond(to req: Request, chainingTo next: Responder) throws -> Future<Response> {
    // make a copy of the path
    var path = req.http.url.path
    
    // path must be relative.
    while path.hasPrefix("/") {
      path = String(path.dropFirst())
    }
    
    // protect against relative paths
    guard !path.contains("../") else {
      throw Abort(.forbidden)
    }
    
    // create absolute file path
    let filePath = publicDirectory + path
    
    if let rangeHeader = req.http.headers.firstValue(name: HTTPHeaderName.range) {
      if rangeHeader.starts(with: "bytes=") {
        let rangeString = String(rangeHeader.dropFirst(6))
        let split = rangeString.split(separator: "-")
        if split.count == 2, let start = Int(split[0]), let end = Int(split[1]) {
          if let data = NSData(contentsOfFile: filePath) {
            let length = end - start + 1
            if length > 0 { //}, length < data.length {
              let retValue = data.subdata(with: NSRange(location: start, length: length))
              let res = req.response()
              res.http.status = .partialContent
              res.http.headers.add(name: HTTPHeaderName.contentLength, value: "\(length)")
              res.http.headers.add(name: HTTPHeaderName.contentRange, value: "bytes \(start)-\(end)/\(data.length)")
              res.http.headers.add(name: HTTPHeaderName.acceptRanges, value: "bytes")
              res.http.body = HTTPBody(data: retValue)
              return req.eventLoop.newSucceededFuture(result: res)
            }
          }
        }
      }
    }
    
    // check if file exists and is not a directory
    var isDir: ObjCBool = false
    guard FileManager.default.fileExists(atPath: filePath, isDirectory: &isDir), !isDir.boolValue else {
      return try next.respond(to: req)
    }
    
    // stream the file
    return try req.streamFile(at: filePath)
  }
}
```

Folks looking for a quick fix can give this a shot.

**Comment by josereyes** [comment]
In case it helps others, I wrote up a custom FileMiddleware to add support for Range Headers and get around this bug for the time being: https://github.com/josereyes/StreamableFileMiddleware/blob/master/StreamableFileMiddleware.swift

**Comment by dylanreich** [comment]
Can confirm @josereyes's solution worked. Hopefully a related solution (aka honoring the Range header) can make it into an official release soon (if not already in the pipeline)!

**Comment by Joannis** [comment]
@tanner0101 I can implement this in FileMiddleware, but that wouldn't solve _all_ use cases. For example, if you were to use the range on JSON data, or a file that's you read from a source other than FileMiddleware supports. 

Maybe we can consider adding a `FileSource` protocol of some kind, to allow files to be served from many sources while respecting these expectations.

```swift
protocol FileSource {
    static func readFileChunk(inRange range: Range<Int>, inReplyTo request: Request) -> EventLoopFuture<ByteBuffer>
}
```

**Comment by keniwhat** [comment]
This discussion seems to be centred on Apple clients behaving differently to other clients for playing media. However byte range requests are part of the HTTP/1.1 standard. Is the goal of this project to fully implement the HTTP standard or just enough for vapor to function as an application server behind a fully compliant HTTP server like nginx? I ask because I would like to know if I should begin implementing my own solution to this gap.  Thanks.

**Comment by 0xTim** [comment]
@keniwhat there's a PR in #2342 that should address this
