### ISSUE TITLE
Precondition failure when write request body into file asyncronously.

### ISSUE THREAD

**Issue by alex1704** [vapor/vapor#2985]
### Describe the bug

I'm implementing upload functionality with HTTPBodyStreamStrategy == .stream. Inside request handler i'm writing data to file in chunks ayncronously. When large file is uploaded precondition failure is executed.

Here is my implementation:  
```
import Vapor
import NIO

func routes(_ app: Application) throws {
    app.on(.POST, "upload", body: .stream, use: { req async throws in
        var offset: Int64 = 0
        let uploads = req.application.directory.workingDirectory.appending("uploads")
        let outPath = "\(uploads)/file"
        try? FileManager.default.createDirectory(atPath: uploads, withIntermediateDirectories: false)
        try? FileManager.default.removeItem(atPath: outPath)
        let fileHandle = try NIOFileHandle(path: outPath, mode: .write, flags: .allowFileCreation())

        for try await buffer in req.body {
            try await req.application.fileio.write(fileHandle: fileHandle,
                                                   toOffset: offset,
                                                   buffer: buffer,
                                                   eventLoop: req.eventLoop).get()
            offset += Int64(buffer.readableBytes)
        }

        try fileHandle.close()
        return "ok"
    })
}
```

### To Reproduce

1) create large file (600M): `mkfile -n 600m file`
2)  `curl -X POST 'http://localhost:8080/upload' --data-binary '@file'`
3) see error
<img width="1387" alt="error" src="https://user-images.githubusercontent.com/1874436/226491344-328a69f9-9203-4789-b28d-42d34b25a24c.png">

Also i noticed that error appear after repeating curl request several times on smaller files, like 100M.

### Expected behavior

No error should happen.   
If i use [futures implementation](https://forums.swift.org/t/how-to-use-nonblockingfileio-for-repeated-writes/36206/24), everything works fine.

### Environment

* Vapor Framework version:  4.74.1
* Vapor Toolbox version: 18.6.0
* OS version: macOS 13.2 (22D49)

**Comment by 0xTim** [comment]
This should now be fixed, feel free to reopen if not!

**Comment by alex1704** [comment]
Still can reproduce. I created hello world project with `upload` endpoint. Additionally added `bigFileTest.sh` script to replicate the issue.
My current environment:
- Vapor:
  - framework: 4.86.2
  - toolbox: 18.7.4
- OS: 13.6 (22G120)
[helloVapor.zip](https://github.com/vapor/vapor/files/13326345/helloVapor.zip)

**Comment by tib** [comment]
I can confirm, this bug still exists in Vapor 4.92.1, any ideas how to fix it? 🤔

**Comment by 0xTim** [comment]
@tib does the `async-streaming-body-client-disconnect` branch fix it?

**Comment by hsharghi** [comment]
> @tib does the `async-streaming-body-client-disconnect` branch fix it?

Can't find the branch

**Comment by 0xTim** [comment]
@hsharghi we've just released https://github.com/vapor/vapor/releases/tag/4.92.3 which has the fix in it

**Comment by 0xTim** [comment]
@alex1704 do you want to confirm it's fixed?

**Comment by alex1704** [comment]
@0xTim sure, will test it later.

**Comment by hsharghi** [comment]
@0xTim The issue still exists

```
Vapor/RequestBody+Concurrency.swift:34: Fatal error

preconditionFailure()              NIO-SGLTN-0-#5 (10): Fatal error
```

**Comment by alex1704** [comment]
yep, can confirm hsharghi message, bug still persists in 4.92.3 version.

**Comment by gulivero1773** [comment]
yep, can confirm hsharghi message, bug still persists in 4.102.0 version.

**Comment by zengadget** [comment]
I'm getting the same crash with 4.102.1, any chance of getting this fixed asap as my whole project depends on Vapor not crashing?

**Comment by zengadget** [comment]
I tried to comment out `preconditionFailure` line in `RequestBody+Concurrency.swift`  ... and now it all works ... 🤓

```
        private func produceMore0() {
            self.eventLoop.preconditionInEventLoop()
            switch self._state {
            case .notCalledYet:
                // We can just return here to sign to the producer that we want more data
                break
            case .noSignalReceived:
                // preconditionFailure()
		break
            case .waitingForSignalFromConsumer(let promise):
                self._state = .noSignalReceived
                promise.succeed(())
            }
        }
``` 

How safe is my approach? I have no idea what .noSignalReceived means. I will do some more testing with some crazy concurrency tests.

**Comment by lmcd** [comment]
Just encountered this in a very large project.  We're gonna have to rip out async code to fix as we can't have our server crashing in production.
Does anyone have any sense of what's causing this?

**Comment by lmcd** [comment]
Also - this is a showstopper bug. There should be a note in the documentation *not* to use this feature, as this *will* crash production servers - until a resolution is found.

**Comment by miroslavkovac** [comment]
I am able to reproduce it without any fileio:

```swift
app.on(.POST, "upload", body: .stream, use: { request async throws in
    let data = request.body.collect(upTo: Int.max)
}
```

This alone is enough to hit the `.noSignalReceived` and crash the server on 4.102.1.

I wonder if Vapor running behind nginxproxy is causing some issues here because I can observe a different behavior in Xcode vs prod. In Xcode the `body.collect()` is relatively fast (~200ms for 100MB file), but on prod this takes ~1min with the same file and actually crashes before it finishes.

**Comment by lmcd** [comment]
I see the crash in Xcode too

**Comment by lmcd** [comment]
I'm having trouble understanding what this code is supposed to do, but I'm seeing `self._state = .noSignalReceived` happening twice. One for a failure path, and another here:

````
        private func produceMore0() {
            self.eventLoop.preconditionInEventLoop()
            switch self._state {
            case .notCalledYet:
                // We can just return here to sign to the producer that we want more data
                break
            case .noSignalReceived:
                preconditionFailure()
            case .waitingForSignalFromConsumer(let promise):
                self._state = .noSignalReceived
                promise.succeed(())
            }
        }
````

Is `noSignalReceived` supposed to be set here?

**Comment by ebariaux** [comment]
I had posted the same issue on the forums (https://forums.swift.org/t/demo-code-of-vapor-v4-image-processing-upload-store-download/66793/12) but apparently it did not get visibility.

I can confirm this still happens with v4.103.1
I did reproduce (systematically) on Linux VM, docker and kubernetes on Intel and in docker and from Xcode on Apple Silicon.
I did a small test project to replicate ([nelcea/Test_FileUpload: Example showing a crash using Vapor for file upload over HTTP](https://github.com/nelcea/Test_FileUpload)) no need to write to a file, just consuming the body bytes causes the issue.

**Comment by gulivero1773** [comment]
Hello, maybe someone have answer?

**Comment by makaGeorge** [comment]
Having the same issue. I didn't see this thread before opening another issue, which I've just closed: https://github.com/vapor/vapor/issues/3227

I guess the solution until this is fixed is to use the old Futures implementation...

**Comment by hsharghi** [comment]
I think this issue won't be fixed as Tim mentioned MultipartKit will be rewritten for vapor 5.

**Comment by 0xTim** [comment]
Just an FYI we're working on this in #3232

**Comment by IgorMuzyka** [comment]
Still getting this crash using vapor `4.106.5`.
<img width="452" alt="screenshot 2024-12-03 at 16 43 48" src="https://github.com/user-attachments/assets/7b55e751-a7c7-476c-a42f-f57906adaf23">
My code which calls to fileio in `Upload.Part.create(from...` looks like this:
```swift
let buffer = try await request.body.collect(upTo: Int(length.rawValue))
let url = destinationDirectory.appendingPathComponent("\(offset).part")
try await request.fileio.writeFile(buffer, at: url.path(percentEncoded: false))
```
Unfortunately i have no idea how to reproduce this.
Curious of what might be the cause, this crash happens on iOS devices which run the server.

**Comment by vzsg** [comment]
Are you sure it's related to this (otherwise very concrete) preconditionFailure? If not, you should open a new issue, and include a complete stacktrace and the actual crash message.

**Comment by 0xTim** [comment]
Yes a complete stack trace would be much better
