### ISSUE TITLE
Toolbox v0.10.2 installation failure in Ubuntu 16.04

### ISSUE THREAD

**Issue by Shunzi007** [vapor/vapor#583]
In Ubuntu 16.04, after command `curl -sL toolbox.vapor.sh | bash
`
> ✅  Compatible
> Downloading...
> Compiling...
> <unknown>:0: error: build had 1 command failures
> error: exit(1): /home/wangshun/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-09-06-a/usr/bin/swift-build-tool -f /home/wangshun/.vapor-toolbox-0.10.2/vapor-toolbox/.build/release.yaml
> Installing...
> bash: line 24: .build/release/Executable: no such file or directory
> Use vapor --help and vapor <command> --help to learn more.

Toolbox v0.10.2 can not be installed

**Comment by Shunzi007** [comment]
Update:
in `/toolbox`, run `swift build -c release`
> Compile Swift Module 'libc' (1 sources)
> Compile Swift Module 'Polymorphic' (2 sources)
> Compile Swift Module 'Core' (29 sources)
> Compile Swift Module 'Console' (34 sources)
> /home/wangshun/toolbox/Packages/Console-0.6.2/Sources/Console/Console/Console.swift:78:49: error: cannot call value of non-function type 'FileHandle'
>             let stdin = FileHandle.standardInput()
>                         ~~~~~~~~~~~~~~~~~~~~~~~~^~
>                                                 
> /home/wangshun/toolbox/Packages/Console-0.6.2/Sources/Console/Console/Console.swift:79:51: error: cannot call value of non-function type 'FileHandle'
>             let stdout = FileHandle.standardOutput()
>                          ~~~~~~~~~~~~~~~~~~~~~~~~~^~
>                                                   
> /home/wangshun/toolbox/Packages/Console-0.6.2/Sources/Console/Console/Console.swift:80:50: error: cannot call value of non-function type 'FileHandle'
>             let stderr = FileHandle.standardError()
>                          ~~~~~~~~~~~~~~~~~~~~~~~~^~
>                                                  
> <unknown>:0: error: build had 1 command failures
> error: exit(1): /home/wangshun/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-09-06-a/usr/bin/swift-build-tool -f /home/wangshun/toolbox/.build/release.yaml

**Comment by LoganWright** [comment]
@Shunzi007 this should resolve it vapor/toolbox#81

**Comment by LoganWright** [comment]
@Shunzi007 merged and ready to go, please try again `curl -sL toolbox.vapor.sh | bash`

**Comment by Shunzi007** [comment]
@LoganWright 
I don't know whether the bug was not fixed or something I missed? I failed again.
> ✅  Compatible
> Downloading...
> Compiling...
> /home/wangshun/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-09-06-a/usr/bin/swift-build: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
> Installing...
> bash: line 22: .build/release/Executable: No such file or directory
> Use vapor --help and vapor <command> --help to learn more.

**Comment by LoganWright** [comment]
@Shunzi007 that looks like the download went well, but when we try to build the toolbox w/ `swift build` it. Can you try just `swift build` and make sure that's all working.

**Comment by Shunzi007** [comment]
it goes well on Ubuntu now！🙃
